name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test atributos
      id: test-atributos
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test atributos
        setup-command: sudo -H pip3 install pytest
        command: pytest testAtributos.py
        timeout: 10
        max-score: 25
    - name: Test metodos
      id: test-metodos
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test metodos
        setup-command: sudo -H pip3 install pytest
        command: pytest testMetodos.py
        timeout: 10
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-ATRIBUTOS_RESULTS: "${{steps.test-atributos.outputs.result}}"
        TEST-METODOS_RESULTS: "${{steps.test-metodos.outputs.result}}"
      with:
        runners: test-atributos,test-metodos
